### ISSUE TITLE
Telescope doesn't show preview for diff_commit_file

### ISSUE THREAD

**Issue by WhiteBlackGoose** [aaronhallaert/ts-advanced-git-search.nvim#1]
Hello. Thanks for this plugin! :heart: 

I'm running 
```
:Telescope advanced_git_search diff_commit_file
```

However, getting 
```
fatal: path 'app-config/nvim/lua/plugins.lua' exists, but not 'lua/plugins.lua'
```
in telescope's preview on the file.

Screenshot:

![image](https://user-images.githubusercontent.com/31178401/222377871-a1a21fc8-1325-404d-8284-839297d09a0e.png)

**Comment by WhiteBlackGoose** [comment]
Also, when I select a commit and hit "enter", it opens an empty buffer

**Comment by aaronhallaert** [comment]
Thanks for reporting this bug!

I could reproduce the issue by opening neovim in a subdirectory of a git repo. The expanded paths are not computed correctly with respect to the root of the git repo, so the git command fails.

I'll open a PR as soon as possible to fix the issue. 
In the meantime, a temporary solution is to open `nvim` at the root of your git repository, this should resolve the problem.
